import re

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Baltistani,Balochi,Balte,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Bravi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,brahvi ,Pashto,pashto,Pastho,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Alhumdulillah Punjabi,Balochi,Siraiki,Bravhi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Baltistani,Urdu,Dari,Balochi,Pashto,Punjabi ,urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,pashto,Persian,Pashto,Urdu,urdu,urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request.replace('Urdu,urdu', 'Urdu'))
(re.sub('Urdu|urdu', 'Urdu', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Baltistani,Balochi,Balte,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Bravi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,brahvi ,Pashto,pashto,Pastho,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Alhumdulillah Punjabi,Balochi,Siraiki,Bravhi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Baltistani,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request.replace('punjabi,Punjabi,pujabi,Allhamduillah punjabi', 'Punjabi'))
(re.sub('punjabi|Punjabi|pujabi|Alhumdulillah Punjabi', 'Punjabi', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Baltistani,Balochi,Balte,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Bravi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,brahvi ,Pashto,pashto,Pastho,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Bravhi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Baltistani,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request .replace('brahvi,Bravi,Brahvi,brahui,Bravhi', 'Brahvi'))
(re.sub('brahvi|Bravi|Brahvi|brahu|Bravhi', 'Brahvi', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Baltistani,Balochi,Balte,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Brahvi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,Brahvi ,Pashto,pashto,Pastho,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,Brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Brahvi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Baltistani,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request .replace('Baltistani,Balte,balti', 'Balti'))
(re.sub('Baltistani|Balte|balti', 'Balti', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Balti,Balochi,Balti,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Brahvi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,Brahvi ,Pashto,pashto,Pastho,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,Brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Brahvi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Balti,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request .replace('Balochi,baloch,Baloch', 'Balochi'))
(re.sub('Balochi|baloch|Baloch', 'Balochi', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Balti,Balochi,Balti,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Brahvi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,Brahvi ,Pashto,pashto,Pastho,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,Brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Brahvi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Balti,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request  .replace('pashto,Pastho,Pustho', 'Pastho'))
(re.sub('pashto|Pastho|Pustho', 'Pashto', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Balti,Balochi,Balti,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Brahvi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,Brahvi ,Pashto,Pashto,Pashto,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,Brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Brahvi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Balti,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,Pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request   .replace('sindhi,Sindhi', 'Sindhi'))
(re.sub('sindhi|Sindhi', 'Sindhi', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Balti,Balochi,Balti,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Brahvi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,Brahvi ,Pashto,Pashto,Pashto,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,Brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Brahvi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Balti,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,Pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
(veggie_request  .replace('siriki,Siriki', 'Siriki'))
(re.sub('siriki|Siriki', 'Siriki', veggie_request))

veggie_request = 'Balochi,Pashto,Pashto,Punjabi,Balti,Balochi,Balti,Punjabi,Balochi,Brahvi,Balochi,Balti,Farsi,Balochi,Balti,Urdu,Pashto,Balochi,Pashto,Panjabi,Pashto,Pashto,Balochi,Pashto ,Pashto,Balti,Punjabi,kaleem,Balochi,Punjabi,Sindhi,Brahvi,Pashto, Punjabi,Balochi,Pashto,Pashto,Pashto ,Brahvi,Balochi,Urdu,Pashto,Balochi ,Brahvi ,Pashto,Pashto,Pashto,Pashto,Punjabi,Brahui ,Pashto,Pashto,Pashto,Pushto,Persian,Brahvi,Pashto,Pushto,Brahvi,Pashto,Dehwari,Urdu,Punjabi ,Balochi ,Pashto,Urdu,Balochi,Urdu,Balochi,Balochi,Balochi,Punjabi ,Punjabi,Balochi,Siraiki,Brahvi,Siraiki,Pashto,Urdu,Pujabi,Brahvi,Urdu,Urdu,Urdu,Punjabi,Brahvi,Urdu,Balti,Urdu,Dari,Balochi,Pashto,Punjabi ,Urdu,Pashto,Urdu,Pashto,Farsi,Balochi,Pashto,Pashto,Persian,Pashto,Urdu,Urdu,Urdu,Pashto,Panjabi,Urdu,Pashto,Russia,Pashto.'
print(veggie_request     .replace('Persian,Dari,Farsi,Dehwari', 'Persian'))
print(re.sub('Persian|Dari|Farsi|Dehwari', 'Persian', veggie_request))

